name: Manual Dependabot trigger

on:
  workflow_dispatch:
    inputs:
      package-ecosystem:
        description: 'Package ecosystem to check (devcontainers/terraform/pip/docker/github-actions)'
        required: true
        type: choice
        options:
          - devcontainers
          - terraform
          - pip
          - docker
          - github-actions

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check team membership
        id: check-team
        run: |
          IS_MEMBER=$(gh api /orgs/${{ github.repository_owner }}/teams/devops/memberships/${{ github.actor }} --silent && echo "true" || echo "false")
          echo "is_member=$IS_MEMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check out code
        if: steps.check-team.outputs.is_member == 'true'
        uses: actions/checkout@v4

      - name: Enable Dependabot
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/dependabot/updates \
            -f package-ecosystem='${{ inputs.package-ecosystem }}' \
            -f directory='/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 