name: Secret Scan

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC

jobs:
  security-scan:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/loonar-git/loonar-morpheus-template:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Run trufflehog scan
      run: |
        # Configura o diretório como seguro
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
        echo "🔍 Iniciando varredura do repositório em busca de segredos..."
        
        if trufflehog --json --regex --entropy=True --max_depth=50 "$GITHUB_WORKSPACE" > trufflehog_output.json; then
          echo "✅ Nenhum segredo encontrado!"
        else
          echo "❌ ATENÇÃO: Segredos encontrados no código!"
          echo "Por favor:"
          echo "1. Remova todos os segredos encontrados"
          echo "2. Revogue imediatamente quaisquer tokens ou credenciais expostos"
          echo "3. Utilize variáveis de ambiente ou secrets do GitHub Actions"
          echo "4. Em arquivos de template, use valores de exemplo como 'SEU_SEGREDO_AQUI'"
          echo ""
          echo "Detalhes dos segredos encontrados:"
          cat trufflehog_output.json
          exit 1
        fi 